# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Github Actions Java CI with Maven

on: 
  push:
    branches: [main]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout main branch from GitHub
    - uses: actions/checkout@v2
    
    - name: Step 2- Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
    
    - name: Step 3 - Have Github Actions Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Step 4 - Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1.1.0
      with:
          project-token: ${{secrets.CODACY_PROJECT_TOKEN}}
          
    - name : Step 5 - List the current directory
      run : ls -a
      
    - name : Step 6
      run: |
        cd target
        ls -a
          
  deploy:
    runs-on: ubuntu-latest
    if: ${{github.ref == 'refs/origin/main' }}
    steps:
    - uses: actions/checkout@v1
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
         heroku_api_key:  ${{secrets.HEROKU_API_KEY}}
         heroku_app_name: "iteaching-production-sprint1"
         heroku_email: "iteaching.sa@gmail.com"
